### ISSUE TITLE
Determining location in Node.js

### ISSUE THREAD

**Issue by franciscop** [umami-software/node#3]
How do you make sure to pass the proper data to determine the location with Umami? Country-level would def be enough for me, I'd guess it's either with the `IP` or with the `language` region? So what kind of option can I set in Node.js for this?

**Comment by mikecao** [comment]
You don't need to pass anything. Umami will figure it our from the IP alone.

**Comment by franciscop** [comment]
Sorry, this is in Node.js, so how does Umami know the IP with this code? When using e.g. Express, wouldn't I need to pass the IP of the client somehow? I believe right now Umami is receiving+using my hosting provider's IP address instead of the client's one with this code:

```js
import umami from '@umami/node';

umami.init({
  websiteId: '...', // Your website id
  hostUrl: '...'
});

// Where do I put either `req` or `ip`?
var ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress 

// Without passing an IP, the "IP" of this request is the hosting one, not the client's one
umami.track({ url: '/home' });
```

**Comment by franciscop** [comment]
Never mind, I found this to know how to pass it!

https://github.com/umami-software/umami/issues/814

**Comment by Sov3rain** [comment]
@franciscop Sorry to hijack your issue, but even after looking a issue #814, I can't figure out how to pass the correct IP address. Do you mind sharing the correct snippet of code (if applicable) you used or at least indicate which solution worked for you? Thanks!

For reference, I'm using the node library in a Fastify server running on Railway.app hosting service.

**Comment by franciscop** [comment]
Sure, this is what I ended up doing:

https://github.com/franciscop/mini-umami/blob/master/index.js#L47-L55

```js
const res = await fetch(`${host.replace(/\/$/, "")}/api/send`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "User-Agent": userAgent,
    "X-Forwarded-For": ip,
  },
  body: JSON.stringify({ type: "event", payload: { website, ...opts } }),
});
```

Basically pass the IP as the header `X-Forwarded-For`.

**Comment by franciscop** [comment]
@Sov3rain note that the official Node.js client, `@umami/node`, doesn't seem to support this:

https://github.com/umami-software/node/blob/master/index.ts#L43-L50

```js
    return fetch(`${hostUrl}/api/send`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': userAgent || `Mozilla/5.0 Umami/${process.version}`,
      },
      body: JSON.stringify({ type, payload }),
    });
```

You'll need to either write your own code for that, or use my library `mini-umami`:

https://github.com/franciscop/mini-umami

**Comment by Sov3rain** [comment]
Thank you very much for your quick answer!
